version: '3'
services:
  nextjs:
    build: ./
    # container_name: nextjs-container
    # image: nextjs-container:1.0.0
    ports:
      - '3000:3000'
      # - "3000:80"
    # environment:
      # - NEXT_PUBLIC_APIHOST_FASTAPI=fastapi:4000
      # - NEXT_PUBLIC_APIHOST_GOLANG=golang:5000
    image: takuyayone/nextjs-sample:1.0.0

  # fastapi:
  #   # build: ./
  #   # container_name: nextjs-container
  #   # image: nextjs-container:1.0.0
  #   ports:
  #     - '4000:4000'
  #     # - "3000:80"
  #   # environment:
  #   #   - NEXT_PUBLIC_APIHOST_FASTAPI=http://production
  #   image: takuyayone/fastapi-sample:1.0.0