version: '3'
services:
  nextjs:
    build: ./
    # container_name: nextjs-container
    # image: nextjs-container:1.0.0
    ports:
      - '3000:3000'
      # - "3000:80"
    environment:
      - NEXT_PUBLIC_APIHOST=http://production
    image: takuyayone/nextjs-sample:1.0.0