apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextjs-nodeport
  name: nextjs-nodeport
  namespace: sandbox
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30300
  selector:
    app: nextjs-dep
  type: NodePort
status:
  loadBalancer: {}
