apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextjs-dep
  name: nextjs-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextjs-dep
    spec:
      containers:
      - image: takuyayone/nextjs-sample:1.0.0
        name: nextjs-sample
        resources: {}
        env:
        - name: NEXT_PUBLIC_APIHOST
          value: fastapi-nodeport:4000
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 30
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 30
          initialDelaySeconds: 30
          httpGet:
            path: /
            port: 3000
status: {}
