apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextjs-service
  name: nextjs-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nextjs-dep
  type: ClusterIP
status:
  loadBalancer: {}
